{% set version = "2.2.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 9e4cc7ebb41efcd67ece39c39d09fcacadc7ae9d2024fe954bb8149e1b9f7570

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - cartopy >=0.14
    - cf_units >=2
    - cftime
    - dask
    - numpy >=1.14, !=1.15.2
    - pyke
    - scipy
    - six
  run:
    - python
    - cartopy >=0.14
    - cf_units >=2
    - cftime
    - dask
    - matplotlib >=2
    - netcdf4 >=1.4
    - numpy >=1.14, !=1.15.2
    - pyke
    - scipy
    - six

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: http://www.scitools.org.uk/iris
  license: GPL3
  license_family: GPL3
  license_file: README.md
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - dkillick
    - corinnebosley
