travis:
  secure:
    BINSTAR_TOKEN: nNvWQJrxMuAYKMLCzuq+rrrmWF0V/den+n1wJHQ7zU7ix+jbNrpp7m9SosLhBL+EhSJ62cguNtrrA9+MMO/ZJx52Lg/Cm9MTBUoCkZgyaUdrXhoqcCupXmFM2SEirIng7Dw4q+qsQSx8/7ugbphCMmp1YtM6GuY6lQYSBnTJ0NN9OjP1WlpbtFar6HGUuk9uOcjlo4gEFPAvGU+wLIZN9q3HvKMuQjvd624fCXeZnCSMULzcOaIcCq1f2aQ04zS9hL6hgxtiARMnFhykvR6bDtCJOrAP0+mg6n2Yo9jmk7UnNCLtxe+lbxtw/q5hybzjGnoLe6h4yNsdyPEfxqIVM1Wg4oz78wNdDIAKbJAtGcUc3LbyOcNFdM9DuXsIM201d4dZjAvkZtRtWxWvdQcwX1oaAPfrFFZcqBoq/pHEAQUteX7UTEjipA1zWVU4VxHFqhmXoR8zwb/2jTF75jmFDKqvf6FdbW3/1tLdIkDSVJTKxznfwAcOznosjlwrCavKYYCkM6+d4h2dX9ZCg9AtfeUWgYC46OsGYcLZAPZVEEL7p6mSmEC5Hjcjv1kuAqoluVzmEF8cdgHKwp8E9FDVOL/lUlji+hZThzg3OtQfx5UjMUIEbZ4a0SdtMhRrDJSeOyUblGx0A1J210+PSHjciI+WxlgxJ5QuKb9qoYoS78w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
